site_name: WebDevBook
theme: readthedocs
repo_url: https://github.com/scholchr/webdevbook/

markdown_extensions:
    - toc:
        permalink: "#"

nav:
    - 'Home': 'index.md'
    - Angular:
        - 'Allgemein': angular/index.md
        - 'Router': angular/router.md
    - Git:
        - 'Allgemein': git/index.md
        - 'SmartGit': git/smartgit.md
    - Sonstiges:
        - 'CSS': 'css.md'
        - 'Grails': 'grails.md'
        - 'JavaScript': 'javascript.md'
        - 'Python': 'python.md'