site_name: WebDevBook
repo_url: https://github.com/scholchr/webdevbook/

theme:
    language: de
    name: material
    features:
        - navigation.instant
        - navigation.tabs
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode


markdown_extensions:
    - abbr
    - admonition
    - toc:
        permalink: "#"
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.snippets


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
    - 'Home': 'index.md'
    - Angular:
        - 'Angular': angular/index.md
        - 'Router': angular/router.md
    - Git:
        - 'Git': git/index.md
        - 'SmartGit': git/smartgit.md
    - IntelliJ:
        - 'IntelliJ': intellij/index.md
    - IuF:
        - 'Investition und Finanzierung': iuf/index.md
        - 'Schlüsselbegriffe': iuf/schluesselbegriffe.md
    - Spring:
        - 'Spring': spring/index.md
    - Sonstiges:
        - 'CSS': 'css.md'
        - 'Grails': 'grails.md'
        - 'JavaScript': 'javascript.md'
        - 'Python': 'python.md'